---
- hosts: "all"
  sudo: yes
  vars_files:
    - 'vars/s3scality_server.yml'
  tasks:
    - name: install g++
      dnf: name=gcc-c++ state=latest

    - name: install make
      dnf: name=make state=latest 

    - name: install npm
      dnf: name=npm

    - name: install git
      dnf: name=git state=latest

    - name: clone scality.S3 
      git: repo=https://github.com/Scality/S3
         version=master
         dest=/home/vagrant/S3
         force=yes

    - name: install S3 scality
      shell: cd S3 && sudo npm install

    - name: config ip for work with bucket
      shell: cd S3 && sed -i "26s/.*/        'bootstrap' \x3A [{{server_ip}}] /" config.json

