---
- hosts: "all"
  sudo: yes
  tasks:
    - name: install gcc*
      dnf: name=gcc* state=latest

    - name: install make
      dnf: name=make state=latest 

    - name: install npm
      dnf: name=npm

    - name: clone scality.S3 
      git: repo=https://github.com/scality/S3
         dest=/home/vagrant/S3
         force=yes

    - name: install S3 scality
      shell: cd S3 && sudo npm install
